# Usa una imagen base ligera de Apache
FROM httpd:alpine

# Copia el archivo HTML al directorio público del servidor web
COPY index.html /usr/local/apache2/htdocs/

# Expone el puerto 80 del contenedor
EXPOSE 80
