# Usa la imagen base oficial de NGINX en su versión ligera
FROM nginx:alpine

# Reemplaza la configuración por defecto de NGINX con nuestro archivo
COPY nginx.conf /etc/nginx/nginx.conf

# Expone el puerto 80 del contenedor
EXPOSE 80
